### ISSUE TITLE
这个demo不太好 

### ISSUE THREAD

**Issue by batsword** [WnagoiYy/EChartsNet#1]
折线图中 DataTable 分别设置column和row
没有一个方法直接add一个点吗？这种逆天思维如何显示几十万个点呢？

**Comment by batsword** [comment]
哦 datatable开销会不会太大?

**Comment by WnagoiYy** [comment]
DataTable 一般是取自数据库的数据，关于DataTable的开销问题还未测试。有什么好的建议和想法欢迎提出！

**Comment by WnagoiYy** [comment]
新增了一个WpfDemo  欢迎关注！

**Comment by batsword** [comment]
@WnagoiYy 我的意思是 x坐标名是依赖column设置 ，线图的时候这个思维模式比较难扭转。新的demo还没看 ，不过你这种方式也是一种方式，另外一种是cefsharp,后者在未加载完成数据会报libcef异常，正在看
