### ISSUE TITLE
dataZoom支持么？貌似不支持，大数据会不会有问题？

### ISSUE THREAD

**Issue by batsword** [WnagoiYy/EChartsNet#2]
属性映射支持(https://echarts.baidu.com/option.html)：
√	title
√	legend
√	grid
√	xAxis
√	yAxis
polar
radiusAxis
angleAxis
radar
dataZoom
visualMap
tooltip
axisPointer
toolbox
brush
geo
parallel
parallelAxis
singleAxis
timeline
graphic
calendar
dataset
aria
series
color
backgroundColor
√	textStyle
√	animation
√	animationThreshold
√	animationDuration
√	animationEasing
√	animationDelay
√	animationDurationUpdate
√	animationEasingUpdate
√	animationDelayUpdate
√	blendMode
√	hoverLayerThreshold
√	useUTC

**Comment by WnagoiYy** [comment]
你可以将该字段需要的js值添加到CompleteOption类的dataZoom属性。
参考 tooltip:
tooltip = new Tooltip() {
                    trigger = "'item'",
                    formatter = "'{a} <br/>{b} : {c} ({d}%)'"
                }
至于大数据问题，应该不用担心，该库底层还是Echarts库，只是net中搭配了webbrowser，若浏览器和Echarts支持，则可以达到效果。

**Comment by batsword** [comment]
@WnagoiYy 多关注大数据吧 不然也不考虑这种方式，因为cs模式下高性能曲线没几个选的 几乎是收费,没啥我closed先
