### ISSUE TITLE
请问怎样才能支持生成图表的下载

### ISSUE THREAD

**Issue by chenzeng11** [WnagoiYy/EChartsNet#5]
想下载生成的图表，不知道怎样才能支持。
另外，其他图都可以正常显示，饼图没有正常显示，不知道可能是什么原因。

**Comment by WnagoiYy** [comment]
需要将图表保存为图片吗，饼图显示的代码看看

**Comment by WnagoiYy** [comment]
> 想下载生成的图表，不知道怎样才能支持。
> 另外，其他图都可以正常显示，饼图没有正常显示，不知道可能是什么原因。

需要将图表保存为图片吗，饼图显示的代码看看

**Comment by chenzeng11** [comment]
已经解决了，谢谢~
